### ISSUE TITLE
Feature Request: a kitchen sink sample app that folks could fork from to build puter apps

### ISSUE THREAD

**Issue by triptych** [HeyPuter/puter.js#3]
As a developer I would like to have a complete project using puter.js apis - perhaps a To Do List app that shows login, key value, text to speech, ai, file IO, etc. The idea is this is a sample app to get developers up and running quickly with puter.js.

The idea is this: some folks need a working project to understand how all the parts fit together. You create a simple project that shows off all of the puter.js apis in one app. As you evolve your api's you keep this project up to date and folks can learn from it. As you create new api's or update old ones, this app always "works" and can be used by developers to understand your framework.

Also, others could contribute to it to make it more understandable or add features like toolbars etc to conform to the puter.js standards.

If you make it a 'template' in github, it can be easily forked for developers to use and get up to speed quickly.

**Comment by AtkinsSJ** [comment]
Good idea. We do have [the Notepad example](https://github.com/HeyPuter/notepad), is that roughly what you were thinking? It could do with some updates probably.

**Comment by jelveh** [comment]
@triptych I just update [the Notepad example](https://github.com/HeyPuter/notepad) to puter.js V2 and added more uses as well. There should still be a prompt feature, but we could add that a bit later. I'm closing this issue because notepad example is now in a good place to demo most features, also there is more apps coming soon.
